setup.py

chore: use scm

---

.pre-commit-config.yaml
README.md
ape_starknet/ecosystems.py
ape_starknet/transactions.py
setup.py
tests/functional/test_contract.py
tests/projects/project/contracts/MyContract.cairo

fix: issue preventing the use of array arguments

---

ape_starknet/_utils.py
ape_starknet/provider.py
ape_starknet/tokens.py
setup.py
tests/integration/conftest.py
tests/integration/test_accounts.py
tests/integration/test_console.py

chore: upgrade starknet.py

---

.pre-commit-config.yaml
ape_starknet/accounts/__init__.py
ape_starknet/provider.py
setup.py
tests/conftest.py
tests/functional/test_contract.py

Events suddenly were not showing on receipts.
Tracked it down to starknet-devnet: https://github.com/Shard-Labs/starknet-devnet/issues/117
Pin `starknet-devnet`
Also adjusted test

fix: issue causing events not to show up on receipts

---

README.md
ape_starknet/accounts/__init__.py
ape_starknet/ecosystems.py
ape_starknet/provider.py
ape_starknet/transactions.py
setup.cfg
tests/functional/test_contract.py
tests/projects/project/contracts/MyContract.cairo

fixes: #15 
Grab the data and attach it the receipt
See tests!

feat: include return data on receipt

---

README.md
ape_starknet/accounts/__init__.py
ape_starknet/ecosystems.py
ape_starknet/provider.py
ape_starknet/tokens.py
ape_starknet/transactions.py
setup.py
tests/functional/test_contract.py
tests/projects/project/ape-config.yaml
tests/projects/project/contracts/MyContract.cairo
tests/projects/proxy/contracts/Proxy.cairo

feat: add Cairo 0.9 support

---

ape_starknet/__init__.py
ape_starknet/accounts/__init__.py
ape_starknet/accounts/_cli.py
ape_starknet/ecosystems.py
ape_starknet/provider.py
ape_starknet/tokens.py
ape_starknet/transactions.py
ape_starknet/utils/__init__.py
tests/functional/test_contract.py
tests/functional/test_ecosystem.py

If you are interested by such PRs, here is a clean-up to fix issues found by Sourcery.

style: clean-up Sourcery issues

---

README.md
ape_starknet/_utils.py
ape_starknet/accounts/__init__.py
ape_starknet/ecosystems.py
ape_starknet/provider.py
ape_starknet/tokens.py
ape_starknet/transactions.py
ape_starknet/utils/__init__.py
tests/conftest.py
tests/functional/test_contract.py
tests/functional/test_transactions.py
tests/projects/project/contracts/ContractFactory.cairo
tests/projects/project/contracts/MyContract.cairo

(kind of started to) Add support for declare TX.
fixes #32

feat: add declare transactions

---

README.md

docs: fix example in readme

---

tests/functional/test_contract.py
tests/projects/project/contracts/MyContract.cairo

adding a couple missing test cases as I debug something.

test: add missing test cases

---

ape_starknet/provider.py
ape_starknet/transactions.py
tests/functional/test_contract.py

Add a new attribute to invoke TX to ease debugging sessions. And also to ensure we will know early when the next Cairo release will break things.
Add `InvokeFunctionTransaction.returnvalue` attrribute.
Added tests.

feat: add raw return value attribute to invoke TX

---

ape_starknet/ecosystems.py
tests/functional/test_tokens.py

Let's hide implementation details to ease everybody's life.
It will be even more important after #69 because TX return data will then also hide those implementation details.

feat: decode Uint256 values in decode_logs()

---

ape_starknet/accounts/__init__.py
ape_starknet/ecosystems.py
ape_starknet/provider.py
ape_starknet/tokens.py
ape_starknet/utils/__init__.py

fix: always use custom exceptions internally

---

.pre-commit-config.yaml
CONTRIBUTING.md
ape_starknet/ecosystems.py
ape_starknet/provider.py
ape_starknet/transactions.py
ape_starknet/utils/__init__.py
setup.py
tests/conftest.py
tests/functional/test_contract.py
tests/functional/test_ecosystem.py
tests/functional/test_networks.py
tests/functional/test_provider.py
tests/functional/test_receipt.py
tests/functional/test_tokens.py
tests/projects/project/contracts/ContractFactory.cairo
tests/projects/project/contracts/EthContract.vy

chore: support ape version 0.4

---

tests/functional/test_contract.py
tests/functional/test_tokens.py
tests/projects/project/contracts/MyContract.cairo

test: ensure providing a dict argument for a struct works

---

setup.py

chore: pin starknet dependencies

---

ape_starknet/ecosystems.py
ape_starknet/provider.py
ape_starknet/transactions.py
ape_starknet/utils/__init__.py
setup.py

* Upgrade starknet.py
* Upgrade devnet
* Fix arg encodings

chore: upgrade starknet dependencies

---

ape_starknet/provider.py

Added `raise_on_fail` per https://github.com/ApeWorX/ape/pull/957
Added new test to verify

feat!: add raise_on_fail to send_transaction()

---

ape_starknet/accounts/__init__.py
ape_starknet/ecosystems.py
ape_starknet/explorer.py
ape_starknet/utils/__init__.py
ape_starknet/utils/basemodel.py

fix: issue where `deploy_account` used outdated contract type

---

setup.py

chore: upgrade starknet.py to `0.6.2a0`

---

.github/workflows/test.yaml
setup.py

feat: support cairo 0.10.2

---

ape_starknet/accounts/_cli.py

docs: add missing CLI help string

---

README.md
ape_starknet/accounts/__init__.py
ape_starknet/accounts/_cli.py
setup.py
tests/integration/test_accounts.py

fixes: ape-342
fixes: ape-352
- Update README.md to remove Argent-X key-file import description and removed duplicate header of Mainnet Alpha Whitelist Deployment Token
- Update setup.py to include python version 3.10 since starknet-dev and starknet.py are compatible now with 3.10
- Remove function and test for importing Argent-X key-file method

chore: Updating for Tutorial

---

README.md

Add sender=account for empty deploy() methods and fix the example factory contract so people can copy and paste the contract if they want to use it as an example. 
fixes: #APE-384

docs: README deploy and factory contract update

---

ape_starknet/accounts/_cli.py
tests/integration/test_accounts.py

fixes: #127 
fixes: APE-517
Mostly copied approach from Ethereum keyfile accounts.
Make sure when your export an account that you imported (like a browser wallet), that the private key matches.
Note, Starknet sticks to base-10 integer-based private keys, so that is what we use here as well.

feat: export account command

---

README.md
ape_starknet/transactions.py
docs/index.md
docs/methoddocs/utils.md
docs/userguides/contracts.md
docs/userguides/testing.md
setup.py

Condense the README and add more userguides to the documentation.
fixes: #APE-690

docs: refactor README and userguides [APE-690]

---

README.md
docs/userguides/accounts.md
docs/userguides/contracts.md

Fixed various typos, and clarify the wording.
Make some changes to docs.
Read the docs.

docs: fix typos [APE-735]
